project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    self-contained: true
    embed-resources: true  # Embeds all resources (including images) into the HTML
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



